export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const NEW_USER = 'NEW_USER';
export const SELECT_USER = 'SELECT_USER';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_SEAT = 'UPDATE_USER_SEAT';

export const NEW_SEAT = 'NEW_SEAT';
export const SELECT_SEAT = 'SELECT_SEAT';
export const UPDATE_SEAT_INFO = 'UPDATE_SEAT_INFO';
export const DELETE_SEAT = 'DELETE_SEAT';

export const CHANGE_SHOW_BLOCKS = 'CHANGE_SHOW_BLOCKS';

export const INITIALIZE_USERS = 'INITIALIZE_USERS';
export const INITIALIZE_SEATS = 'INITIALIZE_SEATS';