export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const NEW_USER = 'NEW_USER';
export const SELECT_USER = 'SELECT_USER';
export const ALLOCATE_USER = 'ALLOCATE_USER';
export const DEALLOCATE_USER = 'DEALLOCATE_USER';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_SEAT = 'UPDATE_USER_SEAT';
export const SWAP_USERS = 'SWAP_USERS';

export const NEW_SEAT = 'NEW_SEAT';
export const SELECT_SEAT = 'SELECT_SEAT';
export const UPDATE_SEAT_INFO = 'UPDATE_SEAT_INFO';
export const UPDATE_SEAT_USER = 'UPDATE_SEAT_USER';
export const UPDATE_SEAT_LOCATION = 'UPDATE_SEAT_LOCATION';
export const DELETE_SEAT = 'DELETE_SEAT';

export const CHANGE_SHOW_BLOCKS = 'CHANGE_SHOW_BLOCKS';